export const GET_BANK_DATA = 'GET_BANK_DATA';
export const GET_BANK_DATA_ERROR = 'GET_BANK_DATA_ERROR';
export const GET_BANK_DATA_SUCCESS = 'GET_BANK_DATA_SUCCESS';

export const SELECT_BANK_ACCOUNT = 'SELECT_BANK_ACCOUNT';

export const CHANGE_PAGE = 'CHANGE_PAGE';
